---
- name: Gather Extensive Windows System Information with Disk and Health Details
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather full set of system facts
      ansible.windows.setup:
        gather_subset:
          - all
      register: full_system_info

    - name: Get detailed disk information
      community.windows.win_disk_facts:
      register: disk_info

    - name: Check system health (example using a script or command)
      ansible.windows.win_command: "your_health_check_script_or_command"
      register: health_check

    - name: Display all gathered system facts
      debug:
        var: full_system_info.ansible_facts

    - name: Display detailed disk information
      debug:
        var: disk_info.disks

    - name: Display system health information
      debug:
        var: health_check.stdout
