---
- name: Install community.windows collection
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install community.windows collection from Ansible Galaxy
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.windows
      delegate_to: localhost
