---
- name: List installed Ansible Galaxy collections
  hosts: localhost
  gather_facts: no
  tasks:
    - name: List installed collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection list
      register: collections_list

    - name: Show collections list
      ansible.builtin.debug:
        var: collections_list.stdout_lines
