---
- name: Gather Windows System Information
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather only the system facts
      ansible.windows.setup:
        gather_subset:
          - hardware
          - network
          - system
      register: system_info

    - name: Display all gathered system facts
      debug:
        var: system_info.ansible_facts
