---
- hosts: all
  gather_facts: true
  tasks: 
    - name: Get disk facts
      community.windows.win_disk_facts:

    - name: Check if disks are found
      fail:
        msg: "No disk facts found"
      when: ansible_facts.disks is not defined or ansible_facts.disks | length == 0

    - name: Output first disk size
      debug:
        var: ansible_facts.disks[0].size

    - name: Set disk variables
      set_fact:
        disk: "{{ ansible_facts.disks | selectattr('system_disk', 'equalto', true) | first }}"
        disksize_gib_human: "{{ disk.size | filesizeformat(true) }}"
        disksize_gib: "{{ (disk.size / (1024 ** 3)) | round(2) }} GiB"

    - name: Convert first system disk into various formats
      debug:
        msg: "Disk size in GiB: {{ disksize_gib }}, Human-readable format: {{ disksize_gib_human }}"
